trigger:
  branches:
    include: ['*']

jobs:
 - job:
   displayName: "Check Formatting"
   pool:
     vmImage: ubuntu-latest
   steps: 
    - template: ci/install-rust.yml
      parameters:
        toolchain: stable
    - script: rustup component add rustfmt
      displayName: "Add Rustfmt"
    - bash: rustfmt --edition 2018 --check src/lib.rs
      displayName: "Check for properly formatted code"
 - job:
   displayName: "Build & Test"
   pool:
     vmImage: ubuntu-latest
   steps:
    - template: ci/install-rust.yml
      parameters:
        toolchain: $(toolchain)
    - bash: cargo test
      displayName: "Test"
